// <auto-generated />
using Jersey.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jersey.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120015648_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jersey.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatName = "English Premier League",
                            DisplayOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CatName = "International Team",
                            DisplayOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CatName = "Serie A",
                            DisplayOrder = 3
                        });
                });

            modelBuilder.Entity("Jersey.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SleeveType")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Edition = "Fans",
                            Price = 459.0,
                            ProductName = "England International Jersey",
                            Season = "2005-2006",
                            Size = "L",
                            SleeveType = "L"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The first Italian Adidas Kit",
                            Edition = "Fans",
                            Price = 410.0,
                            ProductName = "Italy International Jersey",
                            Season = "2022-2023",
                            Size = "XL",
                            SleeveType = "S"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The 2nd Away Kit on 2025--2026",
                            Edition = "Fans",
                            Price = 699.0,
                            ProductName = "Liverpool Football Club",
                            Season = "2025-2026",
                            Size = "L",
                            SleeveType = "S"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
